// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXNNajZAwhK50JbwKKtBCOtlQ6XCzi2tc',
    appId: '1:1042328799510:web:e3384e28a00bc104f16837',
    messagingSenderId: '1042328799510',
    projectId: 'iti-ecommerce-1b901',
    authDomain: 'iti-ecommerce-1b901.firebaseapp.com',
    storageBucket: 'iti-ecommerce-1b901.appspot.com',
    measurementId: 'G-9Q95JVZ0VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzDtnppzfF78BkA5kdUyzr628x4Fd8hV8',
    appId: '1:1042328799510:android:ca53036ff08eabcbf16837',
    messagingSenderId: '1042328799510',
    projectId: 'iti-ecommerce-1b901',
    storageBucket: 'iti-ecommerce-1b901.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZDC5sBz12qeotLwHU4wG8LzAKAwyvFvI',
    appId: '1:1042328799510:ios:5c9a0e55c827d197f16837',
    messagingSenderId: '1042328799510',
    projectId: 'iti-ecommerce-1b901',
    storageBucket: 'iti-ecommerce-1b901.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZDC5sBz12qeotLwHU4wG8LzAKAwyvFvI',
    appId: '1:1042328799510:ios:5c9a0e55c827d197f16837',
    messagingSenderId: '1042328799510',
    projectId: 'iti-ecommerce-1b901',
    storageBucket: 'iti-ecommerce-1b901.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXNNajZAwhK50JbwKKtBCOtlQ6XCzi2tc',
    appId: '1:1042328799510:web:eb5bba9edce2350ef16837',
    messagingSenderId: '1042328799510',
    projectId: 'iti-ecommerce-1b901',
    authDomain: 'iti-ecommerce-1b901.firebaseapp.com',
    storageBucket: 'iti-ecommerce-1b901.appspot.com',
    measurementId: 'G-WXWPK0TM3R',
  );
}
