// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbZikeyjYJnXhEGDSt8aZPusmAgX95KPM',
    appId: '1:601918759274:web:f2298273641b53186ec513',
    messagingSenderId: '601918759274',
    projectId: 'iti-shop-1b44d',
    authDomain: 'iti-shop-1b44d.firebaseapp.com',
    storageBucket: 'iti-shop-1b44d.appspot.com',
    measurementId: 'G-X11CKJGHWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2QR_JIuLm1b4zYXU9iLw4JSwhlSKITjA',
    appId: '1:601918759274:android:f7c6194e6f1b0e806ec513',
    messagingSenderId: '601918759274',
    projectId: 'iti-shop-1b44d',
    storageBucket: 'iti-shop-1b44d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA0qpaus2qlaYgGlEaOpTIZ9sP0rWpNtU',
    appId: '1:601918759274:ios:f98ab6f820c02d9e6ec513',
    messagingSenderId: '601918759274',
    projectId: 'iti-shop-1b44d',
    storageBucket: 'iti-shop-1b44d.appspot.com',
    iosBundleId: 'com.example.day11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA0qpaus2qlaYgGlEaOpTIZ9sP0rWpNtU',
    appId: '1:601918759274:ios:f98ab6f820c02d9e6ec513',
    messagingSenderId: '601918759274',
    projectId: 'iti-shop-1b44d',
    storageBucket: 'iti-shop-1b44d.appspot.com',
    iosBundleId: 'com.example.day11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbZikeyjYJnXhEGDSt8aZPusmAgX95KPM',
    appId: '1:601918759274:web:9a4fa23732dbfec76ec513',
    messagingSenderId: '601918759274',
    projectId: 'iti-shop-1b44d',
    authDomain: 'iti-shop-1b44d.firebaseapp.com',
    storageBucket: 'iti-shop-1b44d.appspot.com',
    measurementId: 'G-XN0CB0ZF2K',
  );
}
